framework:
    messenger:
        transports:
            async:
                dsn: '%env(RABBITMQ_DSN)%'
                options:
                    exchange:
                        name: messages
                        type: direct
                    queues:
                        messages: ~
                retry_strategy:
                    max_retries: 3
                    delay: 1000
                    multiplier: 2

        routing:
            App\Message\ClientCreatedMessage: async

# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
